### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by lcpt** [berndhahnebach/rebar2#3]
Hi, there.

My question is pretty basic: is there a `readme.md` or something like that? I don't know where to start.

Thanks.

**Comment by lcpt** [comment]
I'm starting by reading the code, it seems well documented.

**Comment by freecadci** [comment]
wow do ask as much you like. Keep in mind. AFAIK ... The structure is like Draft module in FreeCAD but Arch will not be moved in this structure. It might make sense to move back to the Arch module structure.
Ahh if there are German comments just drop a message and I will translate it.
cheers bernd
